TEXTS = {
    "ru": {
        "welcome_new": "Добро пожаловать! Выберите язык:",
        "welcome_back": "С возвращением! Выберите действие:",
        "send_photo": "Отправить фото",
        "settings": "Настройки",
        "language_selected": "Язык выбран! Теперь вы можете использовать бота.",
        "profile": "👤 Профиль пользователя",
        "balance": "💰 Баланс: {balance} кредитов",
        "top_up_balance": "💳 Пополнить баланс",
        "change_language": "🌐 Сменить язык",
        "back_to_menu": "⬅️ Назад в меню",
        "select_new_language": "Выберите новый язык:",
        "language_changed": "Язык успешно изменен!",
        "select_payment_method": "💳 Выберите способ оплаты:",
        "yookassa": "💳 ЮKassa",
        "card_transfer": "🏦 Перевод на карту",
        "sbp": "📱 СБП",
        "enter_amount": "💰 Введите сумму пополнения (в рублях):",
        "amount_error": "❌ Неверная сумма. Введите число больше 0.",
        "payment_processing": "⏳ Обработка платежа...",
        "back_to_settings": "⬅️ Назад в настройки",
        "balance_topped_up": "✅ Баланс успешно пополнен на {amount} рублей!\n💰 Новый баланс: {new_balance} кредитов",
        "select_template": "🎨 Выберите шаблон для генерации изображения:",
        "template_1": "📋 Шаблон 1",
        "template_2": "📋 Шаблон 2",
        "template_3": "📋 Шаблон 3",
        "template_4": "📋 Шаблон 4",
        "template_5": "📋 Шаблон 5",
        "template_6": "📋 Шаблон 6",
        "template_7": "📋 Шаблон 7",
        "template_8": "📋 Шаблон 8",
        "template_9": "📋 Шаблон 9",
        "template_10": "📋 Шаблон 10",
        "template_11": "📋 Шаблон 11",
        "template_12": "📋 Шаблон 12",
        "template_13": "📋 Шаблон 13",
        "template_14": "📋 Шаблон 14",
        "template_15": "📋 Шаблон 15",
        "template_16": "📋 Шаблон 16",
        "template_17": "📋 Шаблон 17",
        "template_18": "📋 Шаблон 18",
        "template_19": "📋 Шаблон 19",
        "template_20": "📋 Шаблон 20",
        "custom_prompt": "✍️ Свой промпт",
        "enter_custom_prompt": "✍️ Введите свой промпт для генерации изображения:",
        "your_prompt": "✍️ Ваш промпт:\n\n{prompt}\n\nЖелаете ли улучшить промпт за 15 кредитов?",
        "improve_prompt": "🔧 Улучшить промпт (15 кредитов)",
        "keep_my_prompt": "✅ Оставить мой",
        "prompt_improved": "🔧 Ваш промпт улучшен! Теперь он звучит более профессионально!",
        "back_to_templates": "⬅️ Назад к шаблонам",
        "insufficient_balance": "❌ Недостаточно кредитов для улучшения промпта. Необходимо: 15, у вас: {balance}",
        "prompt_improvement_cost": "💳 Улучшение промпта стоит 15 кредитов. Ваш баланс: {balance} кредитов",
        "send_photo_for_generation": "📸 Отправьте фото для генерации изображения:\n\n💳 Стоимость генерации: 50 кредитов\n💰 Ваш баланс: {balance} кредитов",
        "generation_in_progress": "⏳ Генерация изображения в процессе...",
        "generation_success": "✅ Изображение успешно сгенерировано!",
        "generation_error": "❌ Ошибка при генерации изображения. Попробуйте еще раз.",
        "try_again": "🔄 Еще раз (50 кредитов)",
        "send_another_photo": "📸 Отправить фото",
        "menu": "🏠 Меню",
        "insufficient_balance_generation": "❌ Недостаточно кредитов для генерации. Необходимо: 50, у вас: {balance}",
        "top_up_balance_suggestion": "💡 Пополните баланс, чтобы продолжить работу с ботом!",
        "generation_cost_info": "💳 Стоимость генерации: 50 кредитов\n💰 Ваш баланс: {balance} кредитов",
        "credits_refunded": "💰 Кредиты возвращены на баланс из-за ошибки генерации",
        "insufficient_balance_message": "❌ Недостаточно кредитов для операции. Необходимо: {required}, у вас: {balance}",
        "top_up_balance_button": "💳 Пополнить баланс",
        "main_menu_button": "🏠 Главное меню"
    },
    "en": {
        "welcome_new": "Welcome! Choose your language:",
        "welcome_back": "Welcome back! Choose an action:",
        "send_photo": "Send Photo",
        "settings": "Settings",
        "language_selected": "Language selected! Now you can use the bot.",
        "profile": "👤 User Profile",
        "balance": "💰 Balance: {balance} credits",
        "top_up_balance": "💳 Top Up Balance",
        "change_language": "🌐 Change Language",
        "back_to_menu": "⬅️ Back to Menu",
        "select_new_language": "Select new language:",
        "language_changed": "Language changed successfully!",
        "select_payment_method": "💳 Select payment method:",
        "yookassa": "💳 YooKassa",
        "card_transfer": "🏦 Card Transfer",
        "sbp": "📱 SBP",
        "enter_amount": "💰 Enter top-up amount (in rubles):",
        "amount_error": "❌ Invalid amount. Enter a number greater than 0.",
        "payment_processing": "⏳ Processing payment...",
        "back_to_settings": "⬅️ Back to Settings",
        "balance_topped_up": "✅ Balance topped up by {amount} rubles!\n💰 New balance: {new_balance} credits",
        "select_template": "🎨 Select a template for image generation:",
        "template_1": "📋 Template 1",
        "template_2": "📋 Template 2",
        "template_3": "📋 Template 3",
        "template_4": "📋 Template 4",
        "template_5": "📋 Template 5",
        "template_6": "📋 Template 6",
        "template_7": "📋 Template 7",
        "template_8": "📋 Template 8",
        "template_9": "📋 Template 9",
        "template_10": "📋 Template 10",
        "template_11": "📋 Template 11",
        "template_12": "📋 Template 12",
        "template_13": "📋 Template 13",
        "template_14": "📋 Template 14",
        "template_15": "📋 Template 15",
        "template_16": "📋 Template 16",
        "template_17": "📋 Template 17",
        "template_18": "📋 Template 18",
        "template_19": "📋 Template 19",
        "template_20": "📋 Template 20",
        "custom_prompt": "✍️ Custom Prompt",
        "enter_custom_prompt": "✍️ Enter your custom prompt for image generation:",
        "your_prompt": "✍️ Your prompt:\n\n{prompt}\n\nWould you like to improve the prompt for 15 credits?",
        "improve_prompt": "🔧 Improve Prompt (15 credits)",
        "keep_my_prompt": "✅ Keep My Prompt",
        "prompt_improved": "🔧 Your prompt has been improved! Now it sounds more professional!",
        "back_to_templates": "⬅️ Back to Templates",
        "insufficient_balance": "❌ Insufficient credits to improve prompt. Required: 15, you have: {balance}",
        "prompt_improvement_cost": "💳 Prompt improvement costs 15 credits. Your balance: {balance} credits",
        "send_photo_for_generation": "📸 Send a photo for image generation:\n\n💳 Generation cost: 50 credits\n💰 Your balance: {balance} credits",
        "generation_in_progress": "⏳ Image generation in progress...",
        "generation_success": "✅ Image generated successfully!",
        "generation_error": "❌ Error during image generation. Please try again.",
        "try_again": "🔄 Try Again (50 credits)",
        "send_another_photo": "📸 Send Photo",
        "menu": "🏠 Menu",
        "insufficient_balance_generation": "❌ Insufficient credits for generation. Required: 50, you have: {balance}",
        "top_up_balance_suggestion": "💡 Top up your balance to continue using the bot!",
        "generation_cost_info": "💳 Generation cost: 50 credits\n💰 Your balance: {balance} credits",
        "credits_refunded": "💰 Credits refunded to balance due to generation error",
        "insufficient_balance_message": "❌ Insufficient credits for operation. Required: {required}, you have: {balance}",
        "top_up_balance_button": "💳 Top Up Balance",
        "main_menu_button": "🏠 Main Menu"
    }
}

def get_text(language, key, **kwargs):
    text = TEXTS.get(language, TEXTS["ru"]).get(key, key)
    return text.format(**kwargs) if kwargs else text
